### ISSUE TITLE
Grunt prettysass breaks the animenu scss code

### ISSUE THREAD

**Issue by hsteel** [catalinred/Animenu#2]
Hi :) Thank you very much for Animenu, it's such a good menu solution. I just thought I should let you know about an issue we've spent the last few hours troubleshooting - basically if the Animenu css/style.scss OR sass/style.scss gets run through prettysass - https://www.npmjs.com/package/grunt-prettysass - it seems to break the menu (all of the parent menu items remain visible, while the children work as they should).

This may just be an issue with our particular Grunt setup, I'm not 100% sure, but just thought I'd flag it with you and also post a solution here for anyone else having a similar problem (I know we could have just included a call to the plain screen.css file in our html but this is for a big website so we wanted to avoid the additional http hit).

Basically we're keeping the exact version of the supplied screen.scss file in a sub-directory of our sass partials, and we've renamed it animenu, i.e. **scss/partials/noprettysass/_animenu.scss**

This is called in our master scss file, e.g.
**@import "partials/noprettysass/animenu";**

In our **prettysass.js** grunt file we've specified the directories to be prettysass-ed, e.g.

module.exports = {
	// Pretty SASS
	default_options: {
		options: {
			alphabetize: true
		},
  		src: ['dev/sitename/scss/*.scss','dev/sitename/scss/partials/*.scss']
	}
};

Then in our **watch.js file** we've included the extra "noprettysass" directory, e.g.

module.exports = {
    // **** Watch ****
	css: {
		files: ['dev/sitename/scss/*.scss','dev/sitename/scss/partials/*.scss','dev/sitename/scss/partials/noprettysass/*.scss'],
		tasks: ['prettysass','sass']
	},
};

When you stop and restart grunt from the command line ("grunt watch") and make a change to any of the .scss files it will re-compile and prettisassify everything **except** for the contents of the "noprettysass" directory as when it hits the prettysass.js file it will realise it hasn't been specifically told to process the contents of that directory, and so it won't.

The result is you can still keep everything neatly in your master.scss file and avoid the extra hit to the server by calling another stylesheet, and you can override the base Animenu styles in a normal sass partial, without risking the menu breaking.

Anyway hope this can help someone else at some stage and save you some hours!

Harmony :)

**Comment by catalinred** [comment]
Hi Harmony,

At first sight, *grunt-prettysass* isn't maintained for over two years and one of its requirements is *grunt ~0.4.0*, while the current stable version is *0.4.5*. 

Maybe the above may cause the issues. I'm not sure either but I'll give it a try when I'll have some spare time.

Thanks for writing and I'm glad to hear you're using Animenu ;)

Red.
